name: Build NumWorks NWA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential cmake python3 python3-pip rsync

    - name: Clone Epsilon SDK
      run: |
        git clone --depth 1 https://github.com/numworks/epsilon.git epsilon

    - name: Copy app into Epsilon
      run: |
        mkdir -p epsilon/apps/sudoku
        rsync -av --exclude='.github' --exclude='epsilon' ./ epsilon/apps/sudoku/

    - name: Register app safely
      run: |
        if [ -f epsilon/apps/Makefile ]; then
          sed -i '/^APPS/s/$/ sudoku/' epsilon/apps/Makefile
          echo "===== APPS line after modification ====="
          grep '^APPS' epsilon/apps/Makefile
        else
          echo "Makefile not found, skipping registration"
        fi

    - name: Build NWA with debug
      run: |
        set -x   # Affiche toutes les commandes
        cd epsilon
        make PLATFORM=n0110 nwa -j2 || true
        echo "===== Build log ====="
        find . -name "*.log" -exec cat {} \;

    - name: List all .nwa files
      run: |
        cd epsilon
        echo "===== Listing all .nwa files ====="
        find . -name "*.nwa"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sudoku-nwa
        path: |
          epsilon/**/*.nwa
